# Generated by Django 5.2.4 on 2025-08-13 14:42

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_rate_usd_to_uah', models.DecimalField(decimal_places=4, default=Decimal('40.0000'), max_digits=12)),
                ('final_amount_uah', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('deactivated', 'Deactivated')], default='new', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='0 — безстроково')),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('monobank_invoice_id', models.CharField(blank=True, default='', max_length=128)),
                ('monobank_invoice_url', models.URLField(blank=True, default='')),
                ('payment_processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Платіжне посилання',
                'verbose_name_plural': 'Платіжні посилання',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Оплата послуг', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('default_contract_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
            ],
            options={
                'verbose_name': 'Налаштування платіжної системи',
                'verbose_name_plural': 'Налаштування платіжної системи',
            },
        ),
    ]
